-- Warm Right first-party website analytics
-- Safe to run more than once in the Supabase SQL Editor.

create table if not exists public.site_analytics_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_name text not null default 'page_view',
  page_path text not null,
  page_title text not null default '',
  referrer text not null default '',
  utm_source text not null default '',
  utm_medium text not null default '',
  utm_campaign text not null default '',
  device_type text not null default 'unknown',
  created_at timestamptz not null default now()
);

create table if not exists public.site_analytics_ip_exclusions (
  id uuid primary key default gen_random_uuid(),
  ip_address text not null unique,
  label text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists site_analytics_events_created_at_idx
  on public.site_analytics_events (created_at desc);

create index if not exists site_analytics_events_page_path_idx
  on public.site_analytics_events (page_path, created_at desc);

create index if not exists site_analytics_events_session_id_idx
  on public.site_analytics_events (session_id, created_at desc);

alter table public.site_analytics_events enable row level security;
alter table public.site_analytics_ip_exclusions enable row level security;

drop policy if exists "Authenticated users can read analytics events" on public.site_analytics_events;
create policy "Authenticated users can read analytics events"
on public.site_analytics_events for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read analytics exclusions" on public.site_analytics_ip_exclusions;
create policy "Authenticated users can read analytics exclusions"
on public.site_analytics_ip_exclusions for select
to authenticated
using (true);

drop policy if exists "Authenticated users can add analytics exclusions" on public.site_analytics_ip_exclusions;
create policy "Authenticated users can add analytics exclusions"
on public.site_analytics_ip_exclusions for insert
to authenticated
with check (auth.uid() = created_by);

drop policy if exists "Authenticated users can update analytics exclusions" on public.site_analytics_ip_exclusions;
create policy "Authenticated users can update analytics exclusions"
on public.site_analytics_ip_exclusions for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete analytics exclusions" on public.site_analytics_ip_exclusions;
create policy "Authenticated users can delete analytics exclusions"
on public.site_analytics_ip_exclusions for delete
to authenticated
using (true);

comment on table public.site_analytics_events is
  'Anonymous first-party website events. Visitor IP addresses are never stored here.';

comment on table public.site_analytics_ip_exclusions is
  'IP addresses explicitly excluded by an administrator from website analytics.';
